### ISSUE TITLE
andoCheck API - browser

### ISSUE THREAD

**Issue by BlaizeKevin** [INT-NIT/AnDO#28]
The API seems not working (well) with Mozilla but It's ok with Chrome.

**Comment by SylvainTakerkart** [comment]
you mean GUI, not API, right?

**Comment by Slowblitz** [comment]
Yes but it's my fault :
![image](https://user-images.githubusercontent.com/17256769/92401131-5a5ba800-f12d-11ea-9563-0f1e2e6a4fe8.png)

**Comment by SylvainTakerkart** [comment]
;)

**Comment by SylvainTakerkart** [comment]
@Slowblitz to come back to the original question (compatibility in the different browsers), have you done further tests? you can use a windows machine in the open space if needed!

**Comment by JuliaSprenger** [comment]
Is this issue still relevant with the latest version of AnDO not having a web representation?

**Comment by BlaizeKevin** [comment]
You're right, that is not relevant.

**Comment by SylvainTakerkart** [comment]
hmmmm... I thought we actually wanted to put the online version back up at some point... that would not concern @BlaizeKevin immediately because it's for now ephys-only, but we should keep this alive...

anyhow, we can leave this issue closed and re-open a new one once we discuss all this with @JuliaSprenger and @Slowblitz
