### ISSUE TITLE
Speed up data fetching from gin

### ISSUE THREAD

**Issue by JuliaSprenger** [INT-NIT/AnDO#95]
Currently the tests fetching data from gin take quite some time. Probably data are downloaded repeatedly for individual tests instead of being reused.

**Comment by SylvainTakerkart** [comment]
Hi @JuliaSprenger . I think we should not try to optimize this so that the data gets downloaded only once... This will probably lead to something fairly complex in terms of code...

What I propose is to mimic how it's done for the bids validator, which is to have a version of the test dataset that actually has empty files, or at least empty data files... For BEP032, we will need to provide such a dataset so that the official bids validator can work with it... Let's do the same here!

WDYT?

**Comment by SylvainTakerkart** [comment]
to summurize, I think we should distinguish "test datasets" for our unit tests, and "exemple datasets" that the users can download to have a look, play around or investigate...

**Comment by JuliaSprenger** [comment]
Currently these heavy tests are skipped when the tests are running on github, but can be executed locally.
